/**
 * @file src/cli/StateMachine.ts
 * Finite state machine definition for the interactive CLI presentation layer.
 */

export enum AppState {
  MAIN_MENU = 'MAIN_MENU',
  URL_INPUT = 'URL_INPUT',
  URL_INSPECTING = 'URL_INSPECTING',
  FORMAT_SELECTION = 'FORMAT_SELECTION',
  TOOLS_MENU = 'TOOLS_MENU',
  AUDIO_EXTRACT_MENU = 'AUDIO_EXTRACT_MENU',
  CLIP_PROMPT = 'CLIP_PROMPT',
  THUMBNAIL_PROMPT = 'THUMBNAIL_PROMPT',
  SUBTITLES_PROMPT = 'SUBTITLES_PROMPT',
  CUSTOM_FORMAT_INPUT = 'CUSTOM_FORMAT_INPUT',
  SEARCH_PROMPT = 'SEARCH_PROMPT',
  SEARCH_RUNNING = 'SEARCH_RUNNING',
  SEARCH_RESULTS = 'SEARCH_RESULTS',
  BATCH_PROMPT = 'BATCH_PROMPT',
  QUEUE_MONITOR = 'QUEUE_MONITOR',
  HISTORY_VIEW = 'HISTORY_VIEW',
  SETTINGS_VIEW = 'SETTINGS_VIEW',
  COOKIES_PROMPT = 'COOKIES_PROMPT',
  DEPS_CHECK = 'DEPS_CHECK',
  CONFIRM_EXIT = 'CONFIRM_EXIT',
}

export interface StateTransition {
  from: AppState;
  to: AppState;
  payload?: any;
}
